name: hc05_module_controller
description: A remote app to control HC-05 via Bluetooth
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter