name: "Build & Release"

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Temurin is recommended and open-source
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK release
        run: flutter build apk --release

      - name: Rename APK file
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/hc05remotecontroller.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: build/app/outputs/flutter-apk/hc05remotecontroller.apk

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/hc05remotecontroller.apk
          tag: v1.0.0
          token: ${{ secrets.SECRET_KEY }}
          prerelease: true
